import type {Metadata} from "next";
import Link from "next/link";
import NutritionTable from "@/components/content/NutritionTable";
import {categoryLabels,nutritionItems,type NutritionCategory,type NutritionItem} from "@/data/bibibop-nutrition";
import {siteConfig} from "@/config/site";

const pageUrl=`${siteConfig.url}/bibibop-nutrition-facts/`;
export const metadata:Metadata={
  title:"BIBIBOP Nutrition Facts, Menu Calories & Macros",
  description:"Search all 62 BIBIBOP nutrition facts and compare menu calories, protein, carbs, fat, and sodium by base, protein, topping, sauce, side, and beverage.",
  alternates:{canonical:"/bibibop-nutrition-facts/"},
  openGraph:{title:"BIBIBOP Nutrition Facts, Menu Calories & Macros",description:"Search and compare all 62 BIBIBOP menu nutrition entries from the published nutrition sheet.",url:pageUrl,type:"website"},
};

type NutrientKey="calories"|"proteinG"|"sodiumMg"|"carbsG";
const value=(item:NutritionItem,key:NutrientKey)=>item.nutrients[key].value??0;
const ranked=(items:NutritionItem[],key:NutrientKey,direction:"high"|"low"="high")=>[...items].sort((a,b)=>(value(b,key)-value(a,key))*(direction==="high"?1:-1))[0];
const inCategories=(categories:NutritionCategory[])=>nutritionItems.filter(item=>categories.includes(item.category));
const bases=inCategories(["bases"]),proteins=inCategories(["proteins"]),toppings=inCategories(["hot-toppings","cold-toppings"]),sauces=inCategories(["sauces"]),sidesAndDrinks=inCategories(["sides","desserts","coke-beverages","teas-lemonades","honest-kids","kombucha"]);
const comparisons=[
  ["Highest calories",ranked(nutritionItems,"calories"),"calories"],
  ["Lowest calories",ranked(nutritionItems,"calories","low"),"calories"],
  ["Highest protein",ranked(nutritionItems,"proteinG"),"proteinG"],
  ["Highest sodium",ranked(nutritionItems,"sodiumMg"),"sodiumMg"],
  ["Highest carbohydrate",ranked(nutritionItems,"carbsG"),"carbsG"],
] as const;
const units:Record<NutrientKey,string>={calories:"calories",proteinG:"g protein",sodiumMg:"mg sodium",carbsG:"g carbs"};

function CategorySection({id,title,items,children}:{id:string;title:string;items:NutritionItem[];children:React.ReactNode}){const low=ranked(items,"calories","low"),high=ranked(items,"calories"),protein=ranked(items,"proteinG");return <section id={id} className="facts-category-section"><h2>{title}</h2><p>{children}</p><div className="facts-stat-row"><div><span>Lowest calories</span><strong>{low.name}</strong><small>{low.nutrients.calories.display} calories</small></div><div><span>Highest calories</span><strong>{high.name}</strong><small>{high.nutrients.calories.display} calories</small></div><div><span>Most protein</span><strong>{protein.name}</strong><small>{protein.nutrients.proteinG.display} g per listed portion</small></div></div></section>}

export default function NutritionFactsPage(){const schema=[{"@context":"https://schema.org","@type":"CollectionPage",name:"BIBIBOP Nutrition Facts",url:pageUrl,description:"Searchable BIBIBOP menu nutrition facts for 62 published items.",isPartOf:{"@type":"WebSite",name:siteConfig.name,url:siteConfig.url},mainEntity:{"@type":"Dataset",name:"BIBIBOP nutrition facts database",description:"Nutrition values for 62 BIBIBOP menu components transcribed from the published nutrition and allergen sheet.",url:pageUrl,dateModified:siteConfig.source.checkedDate,creator:{"@type":"Organization",name:siteConfig.name,url:siteConfig.url},license:`${siteConfig.url}/terms/#intellectual-property`,distribution:{"@type":"DataDownload",contentUrl:siteConfig.source.pdfUrl,encodingFormat:"application/pdf"}}},{"@context":"https://schema.org","@type":"BreadcrumbList",itemListElement:[{"@type":"ListItem",position:1,name:"Home",item:siteConfig.url},{"@type":"ListItem",position:2,name:"BIBIBOP Nutrition Facts",item:pageUrl}]}];return <>
  {schema.map((data,index)=><script key={index} type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(data).replace(/</g,"\\u003c")}}/>)}
  <div className="content-page nutrition-facts-page"><div className="shell nutrition-facts-shell"><nav className="breadcrumbs" aria-label="Breadcrumb"><Link href="/">Home</Link><span aria-hidden="true">/</span><span aria-current="page">Nutrition Facts</span></nav><header className="facts-hero"><h1>BIBIBOP Nutrition Facts And Menu Calories</h1><p className="lede">Search all 62 published BIBIBOP nutrition entries below. Compare calories, protein, carbohydrates, fat, sodium, allergens, and vegan markings for listed portions, then use the calculator to total a complete order.</p><div className="hero-actions"><Link className="button" href="/#calculator">Build and total your bowl</Link><a className="button-secondary" href="#full-nutrition-table">Search nutrition facts</a></div></header>
  <nav className="facts-category-nav" aria-label="Nutrition fact categories"><a href="#bases-nutrition">Bases</a><a href="#proteins-nutrition">Proteins</a><a href="#toppings-nutrition">Toppings</a><a href="#sauces-nutrition">Sauces</a><a href="#sides-beverages">Sides &amp; beverages</a><a href="#nutrition-comparisons">Comparisons</a><a href="#full-nutrition-table">Full table</a></nav>
  <div className="facts-content">
    <section className="facts-intro"><h2>How to read BIBIBOP nutrition information</h2><p>Each value applies to the listed serving, not necessarily the amount placed in a particular order. BIBIBOP food is prepared by hand, so portions and actual totals can vary. Use the table for item-to-item comparisons and the <Link href="/#calculator">BIBIBOP Nutrition Calculator</Link> for combined meal totals.</p></section>
    <CategorySection id="bases-nutrition" title="BIBIBOP Bases Nutrition" items={bases}>The six listed bases range from leafy greens to rice and noodles. Base portions differ, so compare the serving description alongside calories and carbohydrates. Lemon Turmeric Rice has the highest listed sodium among the bases.</CategorySection>
    <CategorySection id="proteins-nutrition" title="BIBIBOP Proteins Nutrition" items={proteins}>The seven protein choices include chicken, beef, salmon, steak, and tofu. Steak has the highest listed protein per serving, while calories, fat, carbohydrates, and sodium vary meaningfully across the group.</CategorySection>
    <CategorySection id="toppings-nutrition" title="BIBIBOP Toppings Nutrition" items={toppings}>Hot and cold toppings include vegetables, beans, avocado, cheese, and eggs. Several are very low in calories, while avocado and cheese contribute more fat and calories per listed portion.</CategorySection>
    <CategorySection id="sauces-nutrition" title="BIBIBOP Sauces Nutrition" items={sauces}>Sauce servings are generally listed as one fluid ounce, except Sesame Oil at one-quarter fluid ounce. Compare sodium as well as calories because Teriyaki and Gochujang each list several hundred milligrams per serving.</CategorySection>
    <CategorySection id="sides-beverages" title="BIBIBOP Sides And Beverages Nutrition" items={sidesAndDrinks}>This group covers sides, desserts, fountain drinks, teas, lemonades, kids juices, and kombucha. Beverage calories and carbohydrates vary widely, and the two cookies are the highest-calorie individual entries in this group.</CategorySection>
    <section id="nutrition-comparisons"><h2>Highest And Lowest BIBIBOP Nutrition Comparisons</h2><p>These rankings compare the published serving for each item. They are not adjusted per ounce, and tied items may share the same value.</p><div className="comparison-grid">{comparisons.map(([label,item,key])=><article className="comparison-card" key={label}><span>{label}</span><h3>{item.name}</h3><strong>{item.nutrients[key].display} {units[key]}</strong><small>{categoryLabels[item.category]} · {item.portion}</small></article>)}</div><div className="comparison-notes"><h3>Protein, sodium, and carbohydrate context</h3><p>Steak lists 29 g protein per four-ounce serving. Lemon Turmeric Rice lists 1,490 mg sodium per five-ounce serving. Among all entries, the highest carbohydrate values come from sweetened beverages and larger rice-side portions, so drink and side choices can materially change an order total.</p></div></section>
    <section id="full-nutrition-table" className="full-table-section"><h2>Search The Complete BIBIBOP Nutrition Facts Table</h2><p>Search by item name, choose a category, filter items marked vegan, or sort by calories, protein, carbohydrates, fat, or sodium. All 62 rows are present in the page for crawlability.</p><NutritionTable/></section>
    <section id="source-updates" className="source-history"><h2>Nutrition Source Date And Update History</h2><p>This database uses the complete <a href={siteConfig.source.pdfUrl}>BIBIBOP nutrition and allergen PDF</a>, version dated {siteConfig.source.filenameDate}. The sheet itself also displays “{siteConfig.source.footerDate}.” We keep one source version across the table and calculator rather than mixing values from different publication cycles.</p><ol><li><strong>July 12, 2026:</strong> Source link and all 62 transcribed rows checked; automated duplicate-ID and required-field checks passed.</li><li><strong>September 10, 2025:</strong> Date shown in the official PDF filename used for this dataset version.</li></ol><p>Recipes, suppliers, portions, and menu availability can change. Review the <a href={siteConfig.source.pageUrl}>current BIBIBOP nutrition page</a> and contact the restaurant directly when an allergy or medical need requires current confirmation.</p></section>
    <section id="related-guides" className="related-facts-guides"><h2>Related Nutrition Guides And Tools</h2><p>For help interpreting label values, the FDA explains <a href="https://www.fda.gov/food/nutrition-facts-label/daily-value-new-nutrition-and-supplement-facts-labels">Daily Values on the Nutrition Facts label</a>. These calculators can help place individual menu values in the context of a personal daily estimate.</p><div className="related-tool-grid"><Link href="/nutrition-calculators/calorie-calculator/"><strong>Calorie Calculator</strong><span>Estimate maintenance calories and a daily target.</span></Link><Link href="/nutrition-calculators/macro-calculator/"><strong>Macro Calculator</strong><span>Estimate protein, carbohydrate, and fat targets.</span></Link><Link href="/nutrition-calculators/protein-calculator/"><strong>Protein Calculator</strong><span>Estimate a daily protein range.</span></Link><Link href="/nutrition-calculators/carb-calculator/"><strong>Carbohydrate Calculator</strong><span>Convert a calorie percentage into carbohydrate grams.</span></Link></div></section>
    <section className="facts-final-cta"><h2>Calculate Your Complete BIBIBOP Order</h2><p>The table compares individual portions. Add your exact base, protein, toppings, sauces, and extras to see a real-time combined nutrition summary.</p><Link className="button" href="/#calculator">Open the BIBIBOP calculator</Link></section>
  </div></div></div>
  </>}
