import {test,expect} from "@playwright/test";

const articlePaths=[
  "/blog/bibibop-calories-and-nutrition-guide/","/blog/bibibop-menu-first-time-ordering-guide/","/blog/calories-vs-macros-restaurant-bowl/","/blog/bibibop-proteins-compared/","/blog/bibibop-vs-chipotle-nutrition-comparison/",
];

test("homepage calculator flow",async({page})=>{await page.goto("/");await expect(page.getByRole("heading",{name:"BIBIBOP Nutrition Calculator",exact:true})).toBeVisible();await expect(page.locator(".example-grid .card")).toHaveCount(4);await page.getByLabel("Choose bases").selectOption("purple-rice");await expect(page.getByLabel("Nutrition results")).toContainText("170 calories");await page.getByLabel("Choose proteins").selectOption("steak");await expect(page.getByLabel("Nutrition results")).toContainText("400 calories");await expect(page.getByLabel("Nutrition results")).toContainText("Your total order");await page.getByLabel("Remove Steak").click();await expect(page.getByLabel("Nutrition results")).toContainText("170 calories");await page.getByRole("radio",{name:"BIBICUP"}).check();await expect(page.getByLabel("Nutrition results")).toContainText("85 calories");await page.getByRole("button",{name:"Reset calculator"}).click();await expect(page.getByLabel("Nutrition results")).toContainText("Select an ingredient")});

test("blog archives publish articles and derive comparison parents",async({page})=>{await page.goto("/blog/");await expect(page.locator(".blog-post-card")).toHaveCount(5);await expect(page.getByRole("link",{name:"BIBIBOP Calories and Nutrition Guide",exact:true})).toBeVisible();await page.goto("/blog/comparisons/");await expect(page.locator(".blog-post-card")).toHaveCount(2);await page.goto("/blog/comparisons/meal-comparisons/");await expect(page.locator(".blog-post-card")).toHaveCount(1);await page.goto("/blog/comparisons/restaurant-comparisons/");await expect(page.locator(".blog-post-card")).toHaveCount(1)});

test("article SEO, visible FAQs, images, and mobile overflow are sound",async({page})=>{for(const path of articlePaths){await page.goto(path);await expect(page.locator("h1")).toHaveCount(1);await expect(page.locator('link[rel="canonical"]')).toHaveAttribute("href",new RegExp(`${path.replace(/[.*+?^${}()|[\]\\]/g,"\\$&")}$`));await expect(page.locator(".article-featured-image img")).toBeVisible();await expect(page.locator(".article-inline-image")).toHaveCount(2);await expect(page.locator(".article-faq details")).toHaveCount(5);await expect(page.locator('script[type="application/ld+json"]')).toHaveCount(5);const overflow=await page.evaluate(()=>document.documentElement.scrollWidth-document.documentElement.clientWidth);expect(overflow).toBeLessThanOrEqual(1)}});

test("contact validation is native and backend state is honest",async({page})=>{await page.goto("/contact/");await expect(page.getByLabel("Email",{exact:true})).toHaveAttribute("type","email");await expect(page.getByRole("button",{name:"Send message"})).toBeEnabled();await expect(page.getByText("Form security is not configured")).toHaveCount(0)});
test("one h1 appears on representative public pages",async({page})=>{for(const path of ["/","/about/","/author/m-arslan/","/contact/","/privacy-policy/","/nutrition-calculators/calorie-calculator/","/sitemap/",...articlePaths]){await page.goto(path);await expect(page.locator("h1")).toHaveCount(1)}});
test("author attribution and published author archive are visible",async({page})=>{await page.goto("/");await expect(page.getByText("Researched And Written By")).toBeVisible();await page.getByRole("link",{name:/View Full Author Profile/}).click();await expect(page).toHaveURL(/\/author\/m-arslan\/$/);await expect(page.getByRole("heading",{name:"M. Arsalan"})).toBeVisible();await expect(page.locator(".author-post-list article")).toHaveCount(5)});
test("supporting calculator updates live and menu exposes every tool",async({page})=>{await page.goto("/nutrition-calculators/calorie-calculator/");const menu=page.getByRole("button",{name:/Menu/});const dropdown=page.locator('nav[aria-label="Main navigation"] .nav-dropdown:not(.blog-nav-dropdown)');const directory=dropdown.locator(".nav-dropdown-label");await expect(directory).toHaveAttribute("href","/nutrition-calculators/");if(await menu.isVisible()){await menu.click();await page.getByRole("button",{name:"Toggle calculator links"}).click()}else await directory.hover();await expect(dropdown.locator(".nav-dropdown-menu")).toBeVisible();await expect(dropdown.locator(".nav-dropdown-menu a")).toHaveCount(10);const result=page.locator(".health-result.primary strong");const before=await result.textContent();await page.getByLabel("Age",{exact:true}).fill("45");await expect(result).not.toHaveText(before??"")});
