import Calculator from "@/components/calculator/Calculator";
import HomeNutritionSummary from "@/components/content/HomeNutritionSummary";
import { nutritionItems } from "@/data/bibibop-nutrition";
import { calculateNutrition } from "@/lib/calculate-nutrition";
import { siteConfig } from "@/config/site";
import Link from "next/link";
import AuthorBox from "@/components/content/AuthorBox";
import CalculatorShowcase from "@/components/content/CalculatorShowcase";
import HomeBlogShowcase from "@/components/content/HomeBlogShowcase";

const faqs=[
  ["How accurate is the BIBIBOP Nutrition Calculator?","It totals the values in BIBIBOP's downloadable nutrition sheet. The arithmetic is consistent with that source, but hand portions, substitutions, recipe changes, and location practices can make an actual meal different."],
  ["Does the calculator use official BIBIBOP nutrition data?","Yes. The calculator dataset is transcribed from the official downloadable nutrition and allergen PDF. This independent site is not operated by or affiliated with BIBIBOP."],
  ["What nutrition values does the calculator total?","It totals calories, calories from fat, total fat, saturated fat, trans fat, cholesterol, sodium, carbohydrates, dietary fiber, sugars, and protein."],
  ["How does BIBICUP mode work?","The official sheet says BIBICUP base calories use half portions. BIBICUP mode halves selected base values and labels nutrients beyond calories as portion-derived estimates. It does not halve other items."],
  ["Why do the BIBIBOP webpage and PDF show different values?","The two official sources appear to represent different recipes, portions, or update cycles. This calculator avoids mixing versions by using the complete PDF as its single baseline."],
  ["Which BIBIBOP items are marked vegan?","The table and calculator show the vegan marks from the PDF allergen matrix. Use the vegan filter to review them. A vegan mark does not answer every allergen or cross-contact question."],
  ["How does the calculator display allergens?","It combines the PDF's allergen flags and names the selected items that trigger each flag. It also identifies items or categories missing from the official matrix."],
  ["Is BIBIBOP gluten free?","The restaurant publishes its own gluten-related statements, but its PDF also cautions that normal kitchen operations can involve shared preparation and cross-contact. Confirm current practices directly if gluten exposure is a concern."],
  ["Can restaurant portions change the total?","Yes. The official sheet says items are prepared by hand and serving size variations may occur. The calculator represents listed portions, not a measurement of a particular order."],
  ["Is this calculator medical advice?","No. It is an informational arithmetic tool. Ask a qualified professional for guidance tailored to a medical condition, dietary need, or allergy."],
] as const;
const byId=(id:string)=>nutritionItems.find(i=>i.id===id)!;
const rank=(category:string,key:"calories"|"proteinG"|"sodiumMg",mode:"max"|"min"="max")=>nutritionItems.filter(i=>i.category===category).sort((a,b)=>((b.nutrients[key].value??Infinity)-(a.nutrients[key].value??Infinity))*(mode==="max"?1:-1))[0];
const examples=[
  {name:"Lower-calorie example",ids:["crispy-romaine","korean-crispy-chicken","bean-sprouts","cucumbers","spicy-sriracha"]},
  {name:"Higher-protein example",ids:["purple-rice","steak","bean-sprouts","roasted-sesame-broccoli","gochujang"]},
  {name:"Plant-based example",ids:["crispy-romaine","tofu","black-beans","carrots","pickled-red-onion","sesame-oil"]},
  {name:"Lower-sodium example",ids:["crispy-romaine","steak","cucumbers","pickled-red-onion","sesame-oil"]},
].map(x=>({...x,result:calculateNutrition(x.ids.map(id=>({id,quantity:1})),nutritionItems)}));

export default function Home(){const jsonLd=[{"@context":"https://schema.org","@type":"WebSite",name:siteConfig.name,url:siteConfig.url,description:siteConfig.description,publisher:{"@type":"Organization",name:siteConfig.name,url:siteConfig.url}},{"@context":"https://schema.org","@type":"WebApplication",name:siteConfig.name,url:siteConfig.url,description:siteConfig.description,applicationCategory:"HealthApplication",operatingSystem:"Web",offers:{"@type":"Offer",price:"0",priceCurrency:"USD"},publisher:{"@type":"Organization",name:siteConfig.name}},{"@context":"https://schema.org","@type":"FAQPage",mainEntity:faqs.map(([q,a])=>({"@type":"Question",name:q,acceptedAnswer:{"@type":"Answer",text:a}}))}];return <>
  {jsonLd.map((data,i)=><script key={i} type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(data).replace(/</g,"\\u003c")}}/>)}
  <section className="hero"><div className="shell hero-grid"><div className="hero-copy"><h1><span><span className="hero-brand">BIBIBOP</span> Nutrition</span><span>Calculator</span></h1><p className="lede">Build your bowl and instantly total calories, protein, carbs, fat, sodium, and published allergen flags for every selected ingredient.</p><div className="hero-actions"><Link className="button" href="#calculator">Build Your Bowl</Link><Link className="button-secondary" href="/bibibop-nutrition-facts/">Browse Nutrition Facts</Link></div></div><div className="bowl-art"><div className="floating-stat stat-protein"><strong>29 g</strong><span>Top Listed Protein</span></div><svg viewBox="0 0 420 330" role="img" aria-label="An orange bowl with layered ingredients and nutrition bars"><circle cx="210" cy="160" r="145" fill="#f0fdf4"/><path d="M85 155h250c-13 101-58 145-125 145S98 256 85 155Z" fill="#f97316"/><path d="M105 145c45-45 75 24 111-7 39-34 70 28 99 0" fill="none" stroke="#22c55e" strokeWidth="26" strokeLinecap="round"/><path d="M145 112V70M210 112V45M275 112V80" stroke="#111827" strokeWidth="18" strokeLinecap="round"/></svg><div className="floating-stat stat-items"><strong>Live</strong><span>Nutrition Totals</span></div></div></div></section>
  <section id="calculator" className="section calculator-section"><div className="shell"><div className="section-heading"><h2>Build Your Bowl</h2><p>Choose your ingredients and see the nutrition totals update instantly. Selections stay in your browser.</p></div><Calculator/></div></section>
  <section className="section section-white"><nav className="shell jump-links" aria-label="Homepage sections"><Link href="#how-to-use">How To Use It</Link><Link href="#nutrition-overview">Nutrition Overview</Link><Link href="#nutrition-summary">Nutrition Summary</Link><Link href="#frequently-asked-questions">FAQs</Link></nav><article className="shell article">
    <h2 id="how-to-use">How To Use The BIBIBOP Nutrition Calculator</h2><p>Start by choosing Original Bowl or BIBICUP. Add a base, protein, toppings, sauce, or any extras you plan to order. Each dropdown shows the ingredient name, official portion, and BIBIBOP calories before you add it. If you expect a different amount, choose 0.5x, 1.5x, or 2x.</p><p>The result updates in your browser with macros, sodium, vegan marking, and allergen information. Exact, Estimated, and Incomplete labels make it clear how each total was calculated.</p>
    <h2>What the calculator measures</h2><p>A calorie total is only one view of BIBIBOP bowl nutrition. The tool also adds protein, total carbohydrate, total fat, saturated fat, trans fat, dietary fiber, sugars, sodium, and cholesterol. Calories describe energy. Protein, carbs, and fat are macronutrients, while sodium and cholesterol are measured in milligrams on the official sheet.</p><p>These numbers are most useful when compared with your own needs and the rest of what you eat. The FDA's <a href="https://www.fda.gov/food/nutrition-facts-label/daily-value-new-nutrition-and-supplement-facts-labels">Daily Value guidance for nutrition labels</a> explains how percent Daily Value provides context on packaged food labels. This calculator intentionally reports totals without prescribing a target because individual needs differ.</p>
    <h2 id="nutrition-overview">BIBIBOP Nutrition At A Glance</h2><p>The following comparisons come directly from the calculator dataset. Listed serving sizes differ, so these are quick reference points rather than per-ounce rankings.</p><div className="callout-grid">{[["Highest-Calorie Base",rank("bases","calories")],["Highest-Protein Entrée",rank("proteins","proteinG")],["Lowest-Calorie Sauce",rank("sauces","calories","min")],["Highest-Sodium Base",rank("bases","sodiumMg")],["Highest-Sodium Sauce",rank("sauces","sodiumMg")]].map(([label,item])=><div className="card" key={String(label)}><span>{String(label)}</span><strong>{typeof item!=="string"&&item.name}</strong><small>{typeof item!=="string"&&item.portion}</small></div>)}<div className="card"><span>Cookie Calories</span><strong>{byId("chocolate-chip-cookie").nutrients.calories.display} Each</strong><small>Both listed cookies have the same calories</small></div></div>
    <h2>Comparing calories, protein, carbs, fat, and sodium</h2><p>The ingredient pattern matters more than a single headline number. Bases contribute a large share of BIBIBOP carbs in many bowls. Proteins can change both protein and fat. Sauces can add modest calories while contributing substantial sodium, or they can add more fat depending on the recipe. Toppings range from near-zero-calorie vegetables to more energy-dense avocado or cheese.</p><p>For a lower calorie comparison, look at whole combinations rather than removing one ingredient in isolation. For a higher protein comparison, compare the official protein serving values and consider the rest of the bowl. If sodium matters to you, scan both the base and sauce columns. Lemon Turmeric Rice is listed at 1,490 mg sodium, while some sauces add several hundred milligrams per fluid ounce. A bowl with several individually moderate ingredients can still have a larger combined total.</p><p>Fiber and sugars can also clarify two bowls with similar BIBIBOP bowl calories. The table preserves less-than tokens rather than turning them into zero. For calculation only, this site uses 0.5 as an internal estimate for each “&lt;1” token and clearly changes the status to Estimated.</p>
    <section className="examples-section"><h2>Four Data-Based Bowl Examples</h2><p>These examples are generated from the same data and calculation function as the interactive tool. They are illustrations, not medical or dietary recommendations. Listed portions differ.</p><div className="example-grid">{examples.map(e=><div className="card" key={e.name}><h3>{e.name}</h3><strong>{e.result.totals.calories} calories</strong><p>{e.result.totals.proteinG} g protein · {e.result.totals.carbsG} g carbs · {e.result.totals.fatG} g fat</p><small>{e.ids.map(id=>byId(id).name).join(", ")}</small></div>)}</div></section>
    <h2>Original Bowl versus BIBICUP portions</h2><p>The PDF says that base calories for BIBICUP use half portions. It does not say to halve every bowl component. In BIBICUP mode, this calculator applies a 0.5 factor only to selected bases. Calories follow the explicit source instruction. Other base nutrients are also halved as a portion-derived estimate and the result is labeled Estimated. Proteins, toppings, sauces, sides, desserts, and beverages retain their listed serving values.</p><p>This distinction prevents an easy but misleading shortcut. Halving the entire meal would imply a rule the source does not provide. If a location portions a BIBICUP component differently, the actual total can differ.</p>
    <h2>Vegan and BIBIBOP allergen information</h2><p>The vegan result follows the “vegan friendly” marks in the PDF matrix. “All selected items are marked vegan friendly” means every selection has that official mark. It is not a broader certification and does not establish that a meal fits every definition or avoids cross-contact. Beverage categories do not receive vegan marks in the matrix, so adding one can make the combined status unconfirmed.</p><p>For BIBIBOP allergen information, the calculator combines flags for wheat/gluten, dairy, eggs, soy, sesame, fish/shellfish, peanuts, tree nuts, allium, and MSG. It names the ingredient behind each flag. Cucumbers and the Honey Citrus Kale cold topping have nutrition rows but no matching allergen row. Beverage categories also lack allergen-matrix entries. In those situations the site says data was not provided, never “no allergens.”</p><p>Cross-contact remains possible in shared preparation areas. Anyone with a food allergy should review the current <a href={siteConfig.source.pdfUrl}>official BIBIBOP nutrition and allergen sheet</a> and confirm directly with the restaurant before ordering.</p>
    <h2>How to compare choices without “good” or “bad” labels</h2><p>Food choices are contextual. A higher-calorie bowl may be useful in one situation and unsuitable in another. A lower-sodium option can still have other characteristics a person wants to consider. Instead of assigning moral labels, define the comparison you want to make: lower listed calories, more protein per listed serving, less sodium, more fiber, or ingredients marked vegan.</p><p>Then change one component at a time in the calculator. This makes the effect visible and avoids attributing the entire difference to the wrong ingredient. Keep portions in view. One fluid ounce of sauce and five ounces of rice are not directly comparable units, and a restaurant's hand-prepared amount may vary from the sheet.</p>
    <h2 id="nutrition-summary">BIBIBOP Nutrition Summary By Category</h2><p>This compact summary shows the calorie range and highest listed protein item in each broad menu category. Serving sizes differ. Use the full nutrition database to search, filter, and compare all 62 individual entries.</p>
  </article><div className="shell"><HomeNutritionSummary/></div><article className="shell article">
    <h2>Data Accuracy And Official Source Differences</h2><p>The official webpage and downloadable nutrition sheet disagree for several ingredients. For example, the webpage shows 350 calories for Purple Rice while the downloadable sheet lists 170 for its five-ounce base portion. Mixing the two sources would create an inconsistent calculator.</p><p>The calculator therefore uses the complete downloadable sheet for every nutrient total. The <a href={siteConfig.source.pageUrl}>official BIBIBOP nutrition webpage</a> is linked for additional context only.</p><p>Suppliers, recipes, availability, substitutions, and hand preparation can change actual totals. If you notice a possible error, use the <Link href="/contact/">contact page</Link> and include the ingredient, value, and source you reviewed.</p>
    <section className="faq-section"><h2 id="frequently-asked-questions">Frequently Asked Questions</h2><div className="faq">{faqs.map(([q,a])=><details key={q}><summary>{q}</summary><p>{a}</p></details>)}</div></section>
  </article></section>
  <CalculatorShowcase/>
  <HomeBlogShowcase/>
  <section className="section section-white"><article className="shell article"><h2>A Practical Final Check</h2><p>The BIBIBOP nutrition calculator is best used as a transparent comparison tool. Build the order you expect, look beyond calories to protein, carbs, fat, sodium, and allergen flags, and note whether the status is Exact, Estimated, or Incomplete.</p><p>Save or print a summary when comparing two combinations. Include the itemized list so each calorie or macro difference can be traced to a specific ingredient and portion multiplier. If an allergy, medical condition, or precise intake target affects your decision, verify current restaurant information and seek qualified guidance where appropriate.</p></article><div className="shell homepage-author"><AuthorBox/></div></section>
  </>}
