"use client";
import {useMemo,useState} from "react";
import {activityLabels,bmiCategory,bmiMetric,inchesToCm,poundsToKg,round,tdeeFromProfile,type ActivityLevel,type FormulaSex} from "@/lib/health-calculations";
import type {CalculatorSlug} from "@/data/health-calculators";

type UnitSystem="us"|"metric";type Result={label:string;value:string;primary?:boolean};
const number=(value:string)=>Number(value)||0;
const goalAdjustments:Record<string,number>={maintain:0,"lose-slow":-250,lose:-500,"gain-slow":250};
const macroPlans:Record<string,[number,number,number]>={balanced:[30,40,30],amdr:[20,50,30],"higher-protein":[35,35,30],"higher-carb":[25,50,25]};
const proteinGoals:Record<string,{range:[number,number];label:string}>={general:{range:[.8,.8],label:"General adult reference"},active:{range:[1.2,1.4],label:"Regularly active"},endurance:{range:[1.2,1.6],label:"Endurance training"},strength:{range:[1.4,2],label:"Strength training or muscle gain"},older:{range:[1,1.2],label:"Healthy aging, age 65+"}};

export default function HealthCalculator({type}:{type:CalculatorSlug}){
  const [units,setUnits]=useState<UnitSystem>("us");const [sex,setSex]=useState<FormulaSex>("male");const [age,setAge]=useState(30);const [weight,setWeight]=useState(165);const [height,setHeight]=useState(69);
  const [activity,setActivity]=useState<ActivityLevel>("moderate");const [goal,setGoal]=useState("maintain");const [calories,setCalories]=useState(2000);
  const [macroMode,setMacroMode]=useState<"profile"|"manual">("profile");const [macroPlan,setMacroPlan]=useState("balanced");const [customProtein,setCustomProtein]=useState(30);const [customCarbs,setCustomCarbs]=useState(40);const [customFat,setCustomFat]=useState(30);
  const [proteinGoal,setProteinGoal]=useState("general");const [meals,setMeals]=useState(3);const [carbPercent,setCarbPercent]=useState(50);const [fatPercent,setFatPercent]=useState(30);const [maintenance,setMaintenance]=useState(2200);const [deficit,setDeficit]=useState(500);
  const baseProfileTypes=["calorie-calculator","tdee-calculator","bmr-calculator"] as CalculatorSlug[];const usesProfile=baseProfileTypes.includes(type)||type==="macro-calculator"&&macroMode==="profile";const usesBody=usesProfile||type==="bmi-calculator"||type==="protein-calculator";
  const weightKg=units==="us"?poundsToKg(weight):weight;const heightCm=units==="us"?inchesToCm(height):height;const validBody=weightKg>0&&(type==="protein-calculator"||heightCm>0);
  const profile=useMemo(()=>tdeeFromProfile(weightKg,heightCm,age,sex,activity),[weightKg,heightCm,age,sex,activity]);const goalAdjustment=goalAdjustments[goal]??0;const macroCalories=macroMode==="profile"?profile.tdee+goalAdjustment:calories;
  const selectedMacroPlan=useMemo(()=>macroPlan==="custom"?[customProtein,customCarbs,customFat] as [number,number,number]:macroPlans[macroPlan]??macroPlans.balanced,[macroPlan,customProtein,customCarbs,customFat]);const macroTotal=selectedMacroPlan.reduce((sum,value)=>sum+value,0);const macroValid=macroPlan!=="custom"||Math.abs(macroTotal-100)<.01;
  const results=useMemo<Result[]>(()=>{
    if(usesBody&&!validBody||usesProfile&&(age<20||age>100)||type==="macro-calculator"&&(!macroValid||macroCalories<=0))return[];
    if((["carb-calculator","fat-intake-calculator"] as CalculatorSlug[]).includes(type)&&calories<=0||type==="calorie-deficit-calculator"&&maintenance<=0)return[];
    if(type==="bmi-calculator"){const bmi=bmiMetric(weightKg,heightCm);return[{label:"Adult BMI",value:bmi.toFixed(1),primary:true},{label:"CDC screening category",value:bmiCategory(bmi)}]}
    if(type==="bmr-calculator")return[{label:"Estimated resting energy",value:`${round(profile.bmr).toLocaleString()} calories/day`,primary:true}];
    if(type==="tdee-calculator")return[{label:"Estimated TDEE",value:`${round(profile.tdee).toLocaleString()} calories/day`,primary:true},{label:"Estimated resting energy",value:`${round(profile.bmr).toLocaleString()} calories/day`},{label:"Activity multiplier",value:`${activityFactor(activity)}×`}];
    if(type==="calorie-calculator"){const target=profile.tdee+goalAdjustment;return[{label:"Daily calorie target",value:`${round(target).toLocaleString()} calories`,primary:true},{label:"Estimated maintenance",value:`${round(profile.tdee).toLocaleString()} calories/day`},{label:"Goal adjustment",value:`${goalAdjustment>0?"+":""}${goalAdjustment} calories/day`}];}
    if(type==="macro-calculator"){const [protein,carbs,fat]=selectedMacroPlan;return[{label:"Daily calorie target",value:`${round(macroCalories).toLocaleString()} calories`,primary:true},{label:"Protein",value:`${round(macroCalories*protein/100/4)} g/day`},{label:"Carbohydrate",value:`${round(macroCalories*carbs/100/4)} g/day`},{label:"Fat",value:`${round(macroCalories*fat/100/9)} g/day`},{label:"Macro split",value:`${protein}% / ${carbs}% / ${fat}%`}];}
    if(type==="protein-calculator"){const selected=proteinGoals[proteinGoal]??proteinGoals.general;const low=round(weightKg*selected.range[0]);const high=round(weightKg*selected.range[1]);const perMealLow=round(low/meals);const perMealHigh=round(high/meals);return[{label:"Daily protein range",value:low===high?`${low} g/day`:`${low}–${high} g/day`,primary:true},{label:"Planning context",value:selected.label},{label:`If divided across ${meals} meals`,value:perMealLow===perMealHigh?`About ${perMealLow} g/meal`:`About ${perMealLow}–${perMealHigh} g/meal`},{label:"Reference range",value:selected.range[0]===selected.range[1]?`${selected.range[0]} g/kg/day`:`${selected.range[0]}–${selected.range[1]} g/kg/day`}];}
    if(type==="carb-calculator")return[{label:"Carbohydrate",value:`${round(calories*carbPercent/100/4)} g/day`,primary:true},{label:"Calories from carbohydrate",value:`${round(calories*carbPercent/100).toLocaleString()} calories`},{label:"Selected share",value:`${carbPercent}% of daily calories`}];
    if(type==="fat-intake-calculator")return[{label:"Total fat",value:`${round(calories*fatPercent/100/9)} g/day`,primary:true},{label:"Calories from fat",value:`${round(calories*fatPercent/100).toLocaleString()} calories`},{label:"Selected share",value:`${fatPercent}% of daily calories`}];
    const target=Math.max(0,maintenance-deficit);return[{label:"Daily calorie target",value:`${round(target).toLocaleString()} calories`,primary:true},{label:"Maintenance entered",value:`${round(maintenance).toLocaleString()} calories/day`},{label:"Weekly energy deficit",value:`${round(deficit*7).toLocaleString()} calories`}];
  },[type,usesBody,validBody,usesProfile,age,macroValid,macroCalories,calories,maintenance,weightKg,heightCm,profile,activity,goalAdjustment,selectedMacroPlan,proteinGoal,meals,carbPercent,fatPercent,deficit]);
  const lowTarget=type==="calorie-calculator"&&profile.tdee+goalAdjustment<1000||type==="macro-calculator"&&macroCalories<1000||type==="calorie-deficit-calculator"&&maintenance-deficit<1000;
  const setUnitSystem=(next:UnitSystem)=>{if(next===units)return;if(next==="metric"){setWeight(Number(poundsToKg(weight).toFixed(1)));setHeight(Number(inchesToCm(height).toFixed(1)))}else{setWeight(Number((weight/.45359237).toFixed(1)));setHeight(Number((height/2.54).toFixed(1)))}setUnits(next)};
  return <section className="health-calculator" aria-label={`${type.replaceAll("-"," ")} form`}><div className="health-form">
    {type==="macro-calculator"&&<fieldset className="unit-toggle calculator-method"><legend>How should calories be set?</legend><label><input type="radio" checked={macroMode==="profile"} onChange={()=>setMacroMode("profile")}/> Calculate for me</label><label><input type="radio" checked={macroMode==="manual"} onChange={()=>setMacroMode("manual")}/> Enter calories</label></fieldset>}
    {usesBody&&<fieldset className="unit-toggle"><legend>Units</legend><label><input type="radio" checked={units==="us"} onChange={()=>setUnitSystem("us")}/> US units</label><label><input type="radio" checked={units==="metric"} onChange={()=>setUnitSystem("metric")}/> Metric</label></fieldset>}
    {usesProfile&&<div className="health-field-grid"><label>Sex<select value={sex} onChange={e=>setSex(e.target.value as FormulaSex)}><option value="male">Male</option><option value="female">Female</option></select></label><label>Age<input type="number" min="20" max="100" value={age} onChange={e=>setAge(number(e.target.value))}/></label></div>}
    {usesBody&&<div className="health-field-grid"><label>Weight ({units==="us"?"lb":"kg"})<input type="number" min="1" step="0.1" value={weight} onChange={e=>setWeight(number(e.target.value))}/></label>{type!=="protein-calculator"&&<label>Height ({units==="us"?"in":"cm"})<input type="number" min="1" step="0.1" value={height} onChange={e=>setHeight(number(e.target.value))}/></label>}</div>}
    {usesProfile&&<label className="health-field">Activity level<select value={activity} onChange={e=>setActivity(e.target.value as ActivityLevel)}>{Object.entries(activityLabels).map(([value,label])=><option value={value} key={value}>{label}</option>)}</select></label>}
    {(type==="calorie-calculator"||type==="macro-calculator"&&macroMode==="profile")&&<label className="health-field">Goal<select value={goal} onChange={e=>setGoal(e.target.value)}><option value="maintain">Maintain weight</option><option value="lose-slow">Gradual weight loss</option><option value="lose">Weight loss</option><option value="gain-slow">Gradual weight gain</option></select></label>}
    {type==="macro-calculator"&&<>{macroMode==="manual"&&<label className="health-field">Daily calorie target<input type="number" min="1000" max="10000" step="50" value={calories} onChange={e=>setCalories(number(e.target.value))}/></label>}<label className="health-field">Macro approach<select value={macroPlan} onChange={e=>setMacroPlan(e.target.value)}><option value="balanced">Balanced</option><option value="amdr">General DRI pattern</option><option value="higher-protein">Higher protein</option><option value="higher-carb">Higher carbohydrate</option><option value="custom">Custom percentages</option></select></label>{macroPlan==="custom"&&<div className="health-field-grid custom-macros"><label>Protein (%)<input type="number" min="10" max="50" value={customProtein} onChange={e=>setCustomProtein(number(e.target.value))}/></label><label>Carbs (%)<input type="number" min="10" max="70" value={customCarbs} onChange={e=>setCustomCarbs(number(e.target.value))}/></label><label>Fat (%)<input type="number" min="10" max="50" value={customFat} onChange={e=>setCustomFat(number(e.target.value))}/></label></div>}{!macroValid&&<p className="health-inline-error">Custom percentages currently total {macroTotal}%. Adjust them to equal 100%.</p>}</>}
    {type==="protein-calculator"&&<><label className="health-field">Primary goal or activity<select value={proteinGoal} onChange={e=>setProteinGoal(e.target.value)}><option value="general">General adult nutrition</option><option value="active">Regularly active</option><option value="endurance">Endurance training</option><option value="strength">Strength training or muscle gain</option><option value="older">Healthy aging, age 65+</option></select></label><label className="health-field">Meals per day<select value={meals} onChange={e=>setMeals(number(e.target.value))}>{[2,3,4,5,6].map(value=><option value={value} key={value}>{value} meals</option>)}</select></label></>}
    {type==="carb-calculator"&&<><label className="health-field">Daily calories<input type="number" min="1000" max="10000" step="50" value={calories} onChange={e=>setCalories(number(e.target.value))}/></label><label className="health-field">Calories from carbohydrate<select value={carbPercent} onChange={e=>setCarbPercent(number(e.target.value))}>{[45,50,55,60,65].map(value=><option value={value} key={value}>{value}%</option>)}</select></label></>}
    {type==="fat-intake-calculator"&&<><label className="health-field">Daily calories<input type="number" min="1000" max="10000" step="50" value={calories} onChange={e=>setCalories(number(e.target.value))}/></label><label className="health-field">Calories from fat<select value={fatPercent} onChange={e=>setFatPercent(number(e.target.value))}>{[20,25,30,35].map(value=><option value={value} key={value}>{value}%</option>)}</select></label></>}
    {type==="calorie-deficit-calculator"&&<><label className="health-field">Estimated maintenance calories<input type="number" min="1000" max="10000" step="50" value={maintenance} onChange={e=>setMaintenance(number(e.target.value))}/></label><label className="health-field">Daily calorie deficit<select value={deficit} onChange={e=>setDeficit(number(e.target.value))}><option value="250">250 calories</option><option value="500">500 calories</option><option value="750">750 calories</option></select></label></>}
    <p className="health-form-note">Results update instantly. Values stay in your browser and are not submitted.</p>
  </div><aside className="health-results" aria-live="polite" aria-label="Calculator results"><p className="result-kicker">Estimated result</p>{results.length?<div className="health-result-list">{results.map(result=><div className={result.primary?"health-result primary":"health-result"} key={result.label}><span>{result.label}</span><strong>{result.value}</strong></div>)}</div>:<p>Enter valid adult values to see an estimate.</p>}{lowTarget&&<p className="health-low-warning"><strong>Very low target:</strong> This result is below 1,000 calories per day. Do not treat it as a routine self-directed target. Use qualified clinical guidance.</p>}<p className="health-caution">This educational estimate is not a diagnosis or an individualized nutrition prescription. Needs can differ with pregnancy, growth, medications, health conditions, and athletic training.</p></aside></section>;
}
function activityFactor(activity:ActivityLevel){return({sedentary:1.2,light:1.375,moderate:1.55,very:1.725,extra:1.9})[activity]}
